### ISSUE TITLE
YSF TextDraw functions

### ISSUE THREAD

**Issue by Jedrzej94** [BenBurak/Textdraw-Streamer#1]
Hi,

It would be good if you could provide support for YSF per-player textdraws functions. 

https://github.com/IllidanS4/YSF/blob/master/sampsvr_files/pawno/include/YSF.inc#L370

**Comment by BenBurak** [comment]
Hi,

I will provide support as soon as possible.

**Comment by BenBurak** [comment]
Hello again,

I encountered some problems while supporting YSF plugin. Although I enter the textdraw ID correctly, the return values to me are always negative. If you need it, I can add these functions to the plugin. So you don't need YSF plugin.

Return values
`IsValidPlayerTextdraw: 0`
`IsPlayerTextDrawVisible: 0`
`PlayerTextdrawGetString:`
`PlayerTextDrawGetLetterSize: X: 0.000000, Y: 0.000000`
`PlayerTextDrawGetTextSize: X: 0.000000, Y: 0.000000`
`PlayerTextDrawGetPos: X: 0.000000, Y: 0.000000`
`PlayerTextDrawGetColor: 0`
`PlayerTextDrawGetBoxColor: 0`
`PlayerTextDrawGetBackgroundCol: 0`
`PlayerTextDrawGetShadow: 0`
`PlayerTextDrawGetOutline: 0`
`PlayerTextDrawGetFont: 0`
`PlayerTextDrawIsBox: 0`
`PlayerTextDrawIsProportional: 0`
`PlayerTextDrawIsSelectable: 0`
`PlayerTextDrawGetAlignment: 0`
`PlayerTextDrawGetPreviewModel: 0`
`PlayerTextDrawGetPreviewRot: X: 0.000000, Y: 0.000000, Z: 0.000000, Zoom: 0.000000`
`PlayerTextDrawGetPreviewVehCol: 0`

The version I tried to add support to
`0.3DL`

**Comment by Jedrzej94** [comment]
I mean, you can add them as your own. I didn't mean to convert them from YSF or something. It's just some of those functions are mandatory. If you do add them - please keep the same naming convention as YSF does. That way it will be compatible and plug&play

**Comment by BenBurak** [comment]
I will update the plugin at a convenient time based on your recommendation.

**Comment by BenBurak** [comment]
The features you want have been added to the plugin. Thanks for your suggestion.
