### ISSUE TITLE
many my textdraws is missing / not showing

### ISSUE THREAD

**Issue by mhyunata** [BenBurak/Textdraw-Streamer#10]
When i'm using this plugin, many my textdraws won't display to player / missing. i dont know why but if i try to refresh it (re-executing the cmd it display sometimes it doesn't)

**Comment by nexquery** [comment]
Can I see your codes?

**Comment by SugengGod** [comment]
when I don't use the textdraw-streamer
https://media.discordapp.net/attachments/1062270200059285526/1132548467990999070/not_using_ts.png

but when I use the textdraw streamer there are some icons that don't appear
https://media.discordapp.net/attachments/1062270200059285526/1132548448407793746/using_ts.png

**Comment by nexquery** [comment]
> when I don't use the textdraw-streamer https://media.discordapp.net/attachments/1062270200059285526/1132548467990999070/not_using_ts.png
> 
> but when I use the textdraw streamer there are some icons that don't appear https://media.discordapp.net/attachments/1062270200059285526/1132548448407793746/using_ts.png

Show the libraries you use.

**Comment by nexquery** [comment]
Share the IsValidDynamicTextDraw / IsValidDynamicPlayerTextDraw results.

**Comment by nexquery** [comment]
Are you creating the textdraw as a global or player?

**Comment by nexquery** [comment]
Closed for long periods of non-response.
