### ISSUE TITLE
DynamicTextDrawShowForPlayer: An item for this ID could not be found. ID: 0

### ISSUE THREAD

**Issue by ghost** [BenBurak/Textdraw-Streamer#12]
#include a_samp
#include sscanf2
#include Pawn.RakNet
#include weapon-config

#include streamer
#include textdraw-streamer
#include Pawn.CMD
#include easydialog
#include YSI\YSI_Coding\y_hooks
#include YSI\YSI_Core\y_utils
#include YSF

`CMD:tdtest(playerid)
{
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_BG1);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_BG2);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_LINECLOSE);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_CLOSE);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_INFO1);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_SRINFUS);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_INFO2);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_INFO3);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_BGAC1);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_BGAC2);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_USER_DETAILS);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BGAVATAR);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_AVATAR);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_TEXT_AVATAR);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_BBUP);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_BBDOWN);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_ARROW_UP);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_ARROW_DOWN);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_REDBOX);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_DETAILS1_BG1);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_DETAILS1);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_DETAILSINFO);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_SECURITY);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_TEXT_DETAILS);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_BOX_LINECLOSE2);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_SEX);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_TEXT_INFORMATION);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_CREATEPASS);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_CONFIG);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_CHANGENAME);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_TEXT_HTR);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_CLIC_REGISTER);
	DynamicTextDrawShowForPlayer(playerid, TD_REGISTER_SKIN);
	DynamicPlayerTextDrawShow(playerid, TD_REGISTER_STATE[playerid]);
	SelectTextDraw(playerid, 0xFF0000FF);
	return 1;
}`

`
new Text:TD_REGISTER_BOX_BG1;
`
`//OnGameModeInit
	TD_REGISTER_BOX_BG1 = CreateDynamicTextDraw(119.000000, 120.000000, "_");
	DynamicTextDrawFont(TD_REGISTER_BOX_BG1, 0);
	DynamicTextDrawLetterSize(TD_REGISTER_BOX_BG1, 0.600000, 35.049999);
	DynamicTextDrawTextSize(TD_REGISTER_BOX_BG1, 298.500000, 232.000000);
	DynamicTextDrawSetOutline(TD_REGISTER_BOX_BG1, 1);
	DynamicTextDrawSetShadow(TD_REGISTER_BOX_BG1, 0);
	DynamicTextDrawAlignment(TD_REGISTER_BOX_BG1, 2);
	DynamicTextDrawColour(TD_REGISTER_BOX_BG1, -1);
	DynamicTextDrawBackgroundColour(TD_REGISTER_BOX_BG1, 255);
	DynamicTextDrawBoxColour(TD_REGISTER_BOX_BG1, 590430975);
	DynamicTextDrawUseBox(TD_REGISTER_BOX_BG1, 1);
	DynamicTextDrawSetProportional(TD_REGISTER_BOX_BG1, 1);
	DynamicTextDrawSetSelectable(TD_REGISTER_BOX_BG1, 0);`

`public OnCancelDynamicTextDraw(playerid)
{
    return 0;
}

public OnClickDynamicTextDraw(playerid, Text:textid)
{
    return 0;
}

public OnClickDynamicPlayerTextDraw(playerid, PlayerText:textid)
{
    return 0;
}`
why?

**Comment by nexquery** [comment]
Users are complaining about this problem. In order to solve this problem, I need to analyze your game mode.

**Comment by ghost** [comment]
> Users are complaining about this problem. In order to solve this problem, I need to analyze your game mode.

Well, I use a modular gamemode and load only the user register and textdraws functions in main.pwn.

EDIT: resolved. apparently, 'y_hooks' is the problem. I removed it and rewrote my code. Check it out.

**Comment by nexquery** [comment]
I use y_hooks but I don't have this problem. Try adding #include textdraw-streamer at the bottom.
```c
#include a_samp
#include sscanf2
#include Pawn.RakNet
#include weapon-config

#include streamer
#include Pawn.CMD
#include easydialog
#include YSI\YSI_Coding\y_hooks
#include YSI\YSI_Core\y_utils
#include YSF
#include textdraw-streamer
```

**Comment by nexquery** [comment]
fixed
