### ISSUE TITLE
PlayerTextDrawSetPos, PlayerTextDrawSetPreviewRot

### ISSUE THREAD

**Issue by nazpol9** [BenBurak/Textdraw-Streamer#15]
Hi,

I created a playertextdraw.
When I want to change its position, PlayerTextDrawSetPos randomly adds one or two coordinates (for example, I specify X 510, and the textdraw moves to X 511).

PlayerTextDrawSetPreviewRot does not change textdraw rotation at all.

The condition to use TEXT_DRAW_FONT_MODEL_PREVIEW is met.

I suspected it was omp-server not working correctly with texdraws, but when I disabled the plugin I saw that everything was OK.

Plugin version 2.0.3.
Testing on omp-server (windows).

**Comment by nexquery** [comment]
Are you sure you are using the DynamicPlayerTextDrawSetPos function?

Can I also see your code?

**Comment by nexquery** [comment]
Closed for long periods of non-response.
