### ISSUE TITLE
GLIBC_2.34

### ISSUE THREAD

**Issue by ocalasans** [BenBurak/Textdraw-Streamer#19]
I'm getting this error

```
Failed (/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by plugins/textdraw-streamer.so))
```

**Comment by nexquery** [comment]
What is the Linux version you are using?

**Comment by Walkerxinho7** [comment]
> Qual é a versão do Linux que você está usando?

To be honest, I don't know, my computer is Windows, the host I use is Linux.  How can I see it?

**Comment by nexquery** [comment]
Type hostnamectl in the terminal.

**Comment by Walkerxinho7** [comment]
> Type hostnamectl in the terminal.

![Captura de tela 2023-12-17 171001](https://github.com/nexquery/samp-textdraw-streamer/assets/127008180/68f7d3e7-e159-43a6-bf7d-1820c00c9341)

Translation: 'hostnamectl' is not recognized as an internal command
or external, an operable program or a batch file.

**Comment by nexquery** [comment]
You need to use this command on Linux.  If you are using Windows, use textdraw-streamer.dll

**Comment by Walkerxinho7** [comment]
> Você precisa usar este comando no Linux. Se você estiver usando Windows, use textdraw-streamer.dll

My SA:MP hosting is Linux, there is no way to use Windows Plugins.

**Comment by ocalasans** [comment]
My SA:MP hosting is Linux, there is no way to use Windows Plugins.

**Comment by Walkerxinho7** [comment]
> libc.so.6

I found a similar problem with another plugin: https://github.com/bmisiak/samp-precise-timers/issues/9

**Comment by ocalasans** [comment]
> My SA:MP hosting is Linux, there is no way to use Windows Plugins.

I found a similar problem with another plugin: https://github.com/bmisiak/samp-precise-timers/issues/9

**Comment by nexquery** [comment]
Are you sure you are using the [hot fix](https://github.com/nexquery/samp-textdraw-streamer/releases/tag/v2.0.3-hotfix) version?

**Comment by ocalasans** [comment]
Yes, I sent you a friend request on Discord, if you want I can show you better there.
Name: Calasans
User: ocalasans

**Comment by nexquery** [comment]
The problem is related to the hosting company you use. Because it was compiled with GLIBC 2.28. The error you mentioned indicates version 2.34.

**Comment by ocalasans** [comment]
I understand. I will test with other hosting companies. I currently use TextDraw-Streamer version 2.0.2.

**Comment by nexquery** [comment]
okay
