### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by Allxseiggen** [BenBurak/Textdraw-Streamer#2]
Hi, i started using your plugin today because i was forced to by the samp limit and i have a little problem, i get this console errors and don't know why, i don't use this functions so is from your plugin. Can you help me fix them?

https://prnt.sc/114xpo9 - first line is a little debug to se how plugin works :D

**Comment by BenBurak** [comment]
As far as I know, this problem is caused by the old version of the streamer plugin. What is the streamer version you are using?

**Comment by Allxseiggen** [comment]
Hi again, after reading your message i updated the streamer to version 2.9.3 and this problem still exist. I don't know why is there because i don't use that functions in Gamemode.

**Comment by BenBurak** [comment]
Update Streamer Plugin to v2.9.4. If the problem persists, give the names of the plugins you use in the order in server.cfg.

**Comment by Allxseiggen** [comment]
I updated it, the problem still persists, i'm using this plugins : mysql sscanf crashdetect streamer Whirlpool PawnPlus YSF TextdrawStreamer

**Comment by BenBurak** [comment]
I tried the plugins you are using in an empty mode on Windows and I did not get any errors. What is the operating system you are using?

```
----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.DL-R1, (C)2005-2018 SA-MP Team

filterscripts = ""  (string)

Server Plugins
--------------
 Loading plugin: mysql
 >> plugin.mysql: R41-4 successfully loaded.
  Loaded.
 Loading plugin: sscanf


 ===============================

      sscanf plugin loaded.

         Version:  2.8.3

  (c) 2018 Alex "Y_Less" Cole

 ===============================

  Loaded.
 Loading plugin: crashdetect
  CrashDetect plugin 4.20
  Loaded.
 Loading plugin: streamer


*** Streamer Plugin v2.9.4 by Incognito loaded ***

  Loaded.
 Loading plugin: Whirlpool

 ==================

  Whirlpool loaded

 ==================

  Loaded.
 Loading plugin: PawnPlus
 PawnPlus v1.3.2 loaded
 Created by IllidanS4
  Loaded.
 Loading plugin: YSF_DL

 ==============================================
 YSF 2.1 (compiled Nov 14 2020 15:51:12) loaded
  (c) 2008 Alex "Y_Less" Cole
  (c) 2010 - 2018 kurta999
  (c) 2018 - 2020 IllidanS4
 Server version: 0.3.DL R1, Windows
 ==============================================

  Loaded.
 Loading plugin: textdraw-streamer

 ===============================

    Textdraw Streamer Yuklendi

          Surum: 1.0.6

    Developer: Burak (NexoR)

 ===============================

  Loaded.
 Loaded 8 plugins.
 
Started server on port: 7777, with maxplayers: 500 lanmode is OFF.


Filterscripts
---------------
  Loaded 0 filterscripts.

AMX (47069120) loaded
Number of vehicle models: 0
```

**Comment by Allxseiggen** [comment]
Strange.....i'm using windows 10.

**Comment by BenBurak** [comment]
Do you have a chance to uninstall the YSF plugin and try it?
Because the plugin uses some of the PlayerTextdraw functions of the YSF plugin, you may be getting this error.

See: Natives

**Comment by Allxseiggen** [comment]
Yes, i tryed that, and the problem still exists.

**Comment by BenBurak** [comment]
Can you transfer the game mode you use with all its files? So I can quickly detect the problem.

**Comment by Allxseiggen** [comment]
I don't think i will do that, anyway..i think i will change the plugin or i will search for the problem deeply. Thanks for your time.
