### ISSUE TITLE
Stuck Animation & Broken TextDraw

### ISSUE THREAD

**Issue by Wisnoe26** [BenBurak/Textdraw-Streamer#27]
player stuck animation and textdraw broken when reaching 10++ online players
![Screenshot_2024-02-26-02-51-24-665_com discord](https://github.com/nexquery/samp-textdraw-streamer/assets/140087177/acbe6504-bb4e-4cbf-aa80-083f3f852990)
![Screenshot_2024-02-26-02-51-47-405_com discord](https://github.com/nexquery/samp-textdraw-streamer/assets/140087177/3ac8ca6d-0ad2-465a-80b7-c75be58c1a9c)

**Comment by nexquery** [comment]
Try it without using the plugin and share the results.

**Comment by Wisnoe26** [comment]
> Try it without using the plugin and share the results.

![sa-mp-002](https://github.com/nexquery/samp-textdraw-streamer/assets/140087177/20496bae-a7c3-4b29-b55e-3f2ac2b44984)
![sa-mp-004](https://github.com/nexquery/samp-textdraw-streamer/assets/140087177/d36dbd55-0904-4d01-a18c-d16b8d8d9822)
![sa-mp-005](https://github.com/nexquery/samp-textdraw-streamer/assets/140087177/dcbf0ae0-79cb-46ef-92db-f3b26b2d8cd4)
Without plugin Textdraw Normal when player first spawns, when opening inventory textdraw limits are affected.
Using this plugin, the first time the textdraw appears, everything is normal. but when the player reaches more than 10++ the textdraw is damaged, is there a solution?

**Comment by nexquery** [comment]
Contact me on Discord: benburakya
