### ISSUE TITLE
Is it bypass sprite limits?

### ISSUE THREAD

**Issue by NafizRohan** [BenBurak/Textdraw-Streamer#34]
Do your plugin bypass sprite limits? In my case maybe not. How can I fix it? 

![image](https://github.com/nexquery/samp-textdraw-streamer/assets/145891286/8d3a44fc-485e-4315-aafd-f631e5c71f2b)

**Comment by nexquery** [comment]
Sprite limit must be exceeded by the client. It cannot be exceeded by the server. You can show a maximum of 100 sprites.

**Comment by NafizRohan** [comment]
Thanks
