### ISSUE TITLE
DynamicPlayerTextDrawSetPos issue

### ISSUE THREAD

**Issue by mono9nome** [BenBurak/Textdraw-Streamer#39]
DynamicPlayerTextDrawSetPos resets all textdraw values ​​such as color, textsize, lettersize,... only updates the position

**Comment by nexquery** [comment]
What should happen is to update its location anyway.
For other problems, take a video and share it.

**Comment by mono9nome** [comment]
Sorry to bother you, but I figured out what was wrong with my code. Thank you!
