### ISSUE TITLE
failed (/lib/i386-linux-gnu/libc.so.6: version `glibc_2.34'

### ISSUE THREAD

**Issue by Aldisetiawan14** [BenBurak/Textdraw-Streamer#7]
How to Fix it?

in Linux Debian

**Comment by nexquery** [comment]
Upgrade your operating system to Ubuntu.

**Comment by Aldisetiawan14** [comment]
> 
Okey i will try it thanks for Answer

**Comment by nexquery** [comment]
I would appreciate if you let me know the result after trying it.

**Comment by Aldisetiawan14** [comment]
is there a limit textdraw if using this?

**Comment by Aldisetiawan14** [comment]
> I would appreciate if you let me know the result after trying it.
is there a limit textdraw if using this?

**Comment by nexquery** [comment]
> is there a limit textdraw if using this?

If you show 2048 global textdraws at the same time, there is, but none other than that.

The same is true for player textdraw. If you show 256 textdraws at the same time, you will be stuck at the limit, if you don't, you won't be stuck.

**Comment by Aldisetiawan14** [comment]
> 
So is there still a limit in textdraw?

**Comment by nexquery** [comment]
> So is there still a limit in textdraw?

Yes, there is, but we can say that it does not exist because you will not display 256 or 2048 textdraws at the same time.

Let me give a simple example:
```c
new Text:Global[5000];
for(new i = 0; i < 5000; i++)
{
    Global[i] = TextDrawCreate(320.0, 240.0, "TextDraw ID: %d", i);
}
TextDrawShowForPlayer(playerid, Global[4850]);

/*************************************************************************/

new PlayerText:pText[MAX_PLAYERS][5000];
for(new i = 0; i < 5000; i++)
{
    pText[playerid][i] = CreatePlayerTextDraw(playerid, 320.0, 240.0, "PlayerTextDraw ID: %d", i);
}
PlayerTextDrawShow(playerid, pText[playerid][4850]);
```

**Comment by Aldisetiawan14** [comment]
> > So is there still a limit in textdraw?
> 
> Yes, there is, but we can say that it does not exist because you will not display 256 or 2048 textdraws at the same time.
> 
> Let me give a simple example:
> 
> ```c
> new Text:Global[5000];
> for(new i = 0; i < 5000; i++)
> {
>     Global[i] = TextDrawCreate(320.0, 240.0, "TextDraw ID: %d", i);
> }
> TextDrawShowForPlayer(playerid, Global[4850]);
> 
> /*************************************************************************/
> 
> new PlayerText:pText[MAX_PLAYERS][5000];
> for(new i = 0; i < 5000; i++)
> {
>     pText[playerid][i] = CreatePlayerTextDraw(playerid, 320.0, 240.0, "PlayerTextDraw ID: %d", i);
> }
> PlayerTextDrawShow(playerid, pText[playerid][4850]);
> ```

i already install unbuntu and then when i start server nohup samp03svr
error :

[textdraw.streamer] DynamicTextDrawSetString: An item for this ID could not be found

**Comment by nexquery** [comment]
Normally it should tell you which ID it is. Can you tell me your code and what plugins you are using?

**Comment by Aldisetiawan14** [comment]
> Normally it should tell you which ID it is. Can you tell me your code and what plugins you are using?

can i send video you through email or Discord?

**Comment by nexquery** [comment]
Yes, Nexor#4730

**Comment by Aldisetiawan14** [comment]
> Yes, Nexor#4730

Accept Friend My discord : Fraxy

**Comment by nexquery** [comment]
Can you try this version? Also compiled with debian. It should probably work for debian as well.
https://github.com/nexquery/samp-textdraw-streamer/releases/tag/v2.0.0

**Comment by Hugosdf** [comment]
Hi!
I am having the same problem, using Linux Ubuntu 20.04 X86 64 Minimal Latest V1 with the same error Failed (/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by plugins/textdraw-streamer.so))

**Comment by nexquery** [comment]
> Hi! I am having the same problem, using Linux Ubuntu 20.04 X86 64 Minimal Latest V1 with the same error Failed (/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by plugins/textdraw-streamer.so))

Try this version: https://github.com/nexquery/samp-textdraw-streamer/releases/tag/v2.0.3-hotfix

**Comment by Hugosdf** [comment]
> > Oi! Estou tendo o mesmo problema, usando Linux Ubuntu 20.04 X86 64 Minimal Latest V1 com o mesmo erro Failed (/lib/i386-linux-gnu/libc.so.6: versão 'GLIBC_2.34' não encontrada (exigido por plugins/textdraw-streamer.so))
> 
> Experimente esta versão: https://github.com/nexquery/samp-textdraw-streamer/releases/tag/v2.0.3-hotfix

Thank you very much, this served well here :)))
