### ISSUE TITLE
open.mp

### ISSUE THREAD

**Issue by sean6224** [BenBurak/Textdraw-Streamer#8]
/home/sean/Pulpit/noah-1/omp-server: symbol lookup error: /home/sean/Pulpit/noah-1/plugins/textdraw-streamer.so: undefined symbol: _Z9atcprintfIciEjPT_jPKT0_P6tagAMXPiS7_

**Comment by nexquery** [comment]
what is your operating system?

**Comment by sean6224** [comment]
I tested on linux, Windows not tested

**Comment by nexquery** [comment]
I know it's Linux, I'm asking which one. Ubuntu, debian...

**Comment by sean6224** [comment]
Debian(kali)

**Comment by nexquery** [comment]
I tested it on Ubuntu and it was working fine. I'll look into this issue for Debian tomorrow.

**Comment by nexquery** [comment]
Seems to be a Linux related issue, I'll fix it soon.

**Comment by sean6224** [comment]
No problem

**Comment by nexquery** [comment]
I found the problem is due to text formatting. I will fix it shortly.

**Comment by nexquery** [comment]
Can you try this version?
https://github.com/nexquery/samp-textdraw-streamer/releases/tag/v2.0.0

**Comment by sean6224** [comment]
In evening I will test, can I do your plugin to oop?

**Comment by nexquery** [comment]
What do you mean by oop?

**Comment by nexquery** [comment]
fixed
