### ISSUE TITLE
Clickable text drawings don't work

### ISSUE THREAD

**Issue by knightsamp** [BenBurak/Textdraw-Streamer#9]
When I create the text drawings after the plugin this message appears:

```
[textdraw.streamer] DynamicPlayerTextDrawShow: First create the player textdraw.
[textdraw.streamer] DynamicPlayerTextDrawHide: First create the player textdraw.
```

But textdraws inside textdraw-streamer callbacks respond correctly.

When I create the text drawings before the plugin the clickable textdraws don't work.

**Comment by knightsamp** [comment]
So, I wonder, even if the message "first create the player textdraw" appears, if I click and it responds to the callback, does it mean it's working? And I want to know if I'm exceeding the limit or making the message disappear to make it work properly.

**Comment by nexquery** [comment]
Message warning means it's not working properly. You must first create a text drawing with CreatePlayerTextDraw. Can I see your codes and your library order?

**Comment by knightsamp** [comment]
```
#include <a_samp>
#include <a_mysql>
#include <streamer>
#include <sscanf2>
#include <foreach>
#include <YSI\y_timers>
#include <YSI\y_utils>
#include <YSI\y_ini>
#include <YSI\y_hooks>
#include <mapandreas>
#include <colandreas>
#include <Pawn.RakNet>
#include <Pawn.CMD>
#include <textdraw-streamer> // with the include here everything works correctly but when I place the plugin afterwards I can't click on the textdraws

// Textdraws 

#include "textdraws/menu.pwn"
#include "textdraws/compass.pwn"
#include "textdraws/hud.pwn"
#include "textdraws/notifications.pwn"
#include "textdraws/actions.pwn"
```

**Comment by knightsamp** [comment]
Version 1.6.2 worked fine for me but I want to keep up to date

**Comment by nexquery** [comment]
There may be a hooking problem.

**Comment by nexquery** [comment]
Can you try without the hook method?
Using only native.
Example:
```
CreatePlayerTextDraw -> CreateDynamicPlayerTextDraw
```

**Comment by knightsamp** [comment]
it was not solved
maybe I should go back to version 1.6.2

**Comment by nexquery** [comment]
Would you like to share your game mod so I can quickly identify the problem.

**Comment by knightsamp** [comment]
Could you tell me what current callbacks correspond to those of version 1.6.2?
```
warning 235: public function lacks forward declaration (symbol "OnClickDynamicTextDraw")
warning 235: public function lacks forward declaration (symbol "OnClickDynamicPlayerTextDraw")
warning 235: public function lacks forward declaration (symbol "OnCancelDynamicTextDraw")
```

**Comment by nexquery** [comment]
In v1.6.2 the callbacks are different, you can look it up in textdraw-streamer.inc

**Comment by nexquery** [comment]
https://github.com/nexquery/samp-textdraw-streamer/blob/070d11a88c07f4d77ebc87713e10b8ea1246fe93/textdraw-streamer.inc#L75

**Comment by knightsamp** [comment]
selectable textdraws still not working no matter plugin version

**Comment by nexquery** [comment]
Can you add me on discord?
If you share your game mod, I can quickly identify the problem.

Discord: Nexor#4730

**Comment by knightsamp** [comment]
solved 
thanks for the support @nexquery
